//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingDatasourceCredentials.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SettingDatasourceCredentials.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Report MustUnderstand=&quot;df&quot; xmlns=&quot;http://schemas.microsoft.com/sqlserver/reporting/2016/01/reportdefinition&quot; xmlns:rd=&quot;http://schemas.microsoft.com/SQLServer/reporting/reportdesigner&quot; xmlns:df=&quot;http://schemas.microsoft.com/sqlserver/reporting/2016/01/reportdefinition/defaultfontfamily&quot;&gt;
        ///  &lt;rd:ReportUnitType&gt;Inch&lt;/rd:ReportUnitType&gt;
        ///  &lt;rd:ReportID&gt;3d0f194c-6d06-4ddd-91d6-bce550c00543&lt;/rd:ReportID&gt;
        ///  &lt;df:DefaultFontFamily&gt;Segoe UI&lt;/df:DefaultFontFamily&gt;
        ///  &lt;AutoRefresh&gt;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerSalesPaginated_rdl {
            get {
                return ResourceManager.GetString("CustomerSalesPaginated_rdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Dataflow with SQL Datasource for Product List&quot;,
        ///  &quot;description&quot;: &quot;&quot;,
        ///  &quot;version&quot;: &quot;1.0&quot;,
        ///  &quot;culture&quot;: &quot;en-US&quot;,
        ///  &quot;modifiedTime&quot;: &quot;2021-10-10T16:00:27.8391704+00:00&quot;,
        ///  &quot;pbi:mashup&quot;: {
        ///    &quot;fastCombine&quot;: false,
        ///    &quot;allowNativeQueries&quot;: false,
        ///    &quot;queriesMetadata&quot;: {
        ///      &quot;Products&quot;: {
        ///        &quot;queryId&quot;: &quot;67569ba5-c9cd-462b-b17c-378d683aea3f&quot;,
        ///        &quot;queryName&quot;: &quot;Products&quot;,
        ///        &quot;loadEnabled&quot;: true
        ///      },
        ///      &quot;DatabaseServer&quot;: {
        ///        &quot;queryId&quot;: &quot;8182d46d-fcee-42d9-9adc-2bbffae0fe89 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataflowWithSQlDatasource_json {
            get {
                return ResourceManager.GetString("DataflowWithSQlDatasource_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DatasetWithAdlsFileDatasource_pbix {
            get {
                object obj = ResourceManager.GetObject("DatasetWithAdlsFileDatasource_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DatasetWithAnonymousDatasource_pbix {
            get {
                object obj = ResourceManager.GetObject("DatasetWithAnonymousDatasource_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DatasetWithDataflowDatasource_pbix {
            get {
                object obj = ResourceManager.GetObject("DatasetWithDataflowDatasource_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DatasetWithKustoDatasource_pbix {
            get {
                object obj = ResourceManager.GetObject("DatasetWithKustoDatasource_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DatasetWithSharePointFileDatasource_pbix {
            get {
                object obj = ResourceManager.GetObject("DatasetWithSharePointFileDatasource_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DatasetWithSqlDatasource_pbix {
            get {
                object obj = ResourceManager.GetObject("DatasetWithSqlDatasource_pbix", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
